DROP TABLE ARTIST_EVEN CASCADE CONSTRAINTS;
DROP TABLE ORGANIZATIE CASCADE CONSTRAINTS;
DROP TABLE PROGRAM CASCADE CONSTRAINTS;
DROP TABLE RECENZIE CASCADE CONSTRAINTS;
DROP TABLE PARTICIPANT CASCADE CONSTRAINTS;
DROP TABLE PLATA CASCADE CONSTRAINTS;
DROP TABLE EVENIMENT CASCADE CONSTRAINTS;
DROP TABLE TIP_BILET CASCADE CONSTRAINTS;
DROP TABLE ARTIST CASCADE CONSTRAINTS;
DROP TABLE LOCATIE CASCADE CONSTRAINTS;
DROP TABLE CATEGORIE CASCADE CONSTRAINTS;
DROP TABLE ORGANIZATOR CASCADE CONSTRAINTS;
DROP TABLE BILET CASCADE CONSTRAINTS;
DROP SEQUENCE sequence_1;


CREATE SEQUENCE sequence_1
start with 1
increment by 1
minvalue 0
maxvalue 30
cycle;

CREATE TABLE LOCATIE(
    LOCATIE_ID NUMBER(5),
    ADRESA VARCHAR2(80) NOT NULL,
    CAPACITATE INT NOT NULL,
    CONSTRAINT CHEIE_PRIM_LOC PRIMARY KEY (LOCATIE_ID)
);


CREATE TABLE ARTIST(
    ARTIST_ID NUMBER(5),
    NUME VARCHAR2(255) NOT NULL,
    PRIMARY KEY (ARTIST_ID)
);

CREATE TABLE ORGANIZATOR(
    ORGANIZATOR_ID NUMBER(5),
    NUME VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(255) NOT NULL UNIQUE,
    TELEFON NUMBER(10),
    CONSTRAINT CHEIE_PRIM_ORG PRIMARY KEY (ORGANIZATOR_ID)
);

CREATE TABLE CATEGORIE(
    CATEGORIE_ID NUMBER(5),
    NUME VARCHAR2(25) NOT NULL,
    CONSTRAINT CHEIE_PRIM_CATEG PRIMARY KEY (CATEGORIE_ID)
);


CREATE TABLE EVENIMENT (
    EVENIMENT_ID NUMBER(5),
    NUME VARCHAR2(40) NOT NULL,
    DESCRIERE VARCHAR2(150),
    DATA_INCEPUT DATE NOT NULL,
    DATA_FINAL DATE NOT NULL,
    LOCATIE_ID INT,
    CATEGORIE_ID INT,
    CONSTRAINT CHEIE_PRIMARA PRIMARY KEY (EVENIMENT_ID),
    CONSTRAINT fk_locatie FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE(LOCATIE_ID),
    CONSTRAINT fk_categorie FOREIGN KEY (CATEGORIE_ID) REFERENCES CATEGORIE(CATEGORIE_ID)
);


CREATE TABLE ORGANIZATIE(
    EVENIMENT_ID NUMBER(5),
    ORGANIZATOR_ID NUMBER(5),
    PRIMARY KEY (EVENIMENT_ID, ORGANIZATOR_ID),
    FOREIGN KEY (EVENIMENT_ID) REFERENCES EVENIMENT(EVENIMENT_ID),
    FOREIGN KEY (ORGANIZATOR_ID) REFERENCES ORGANIZATOR(ORGANIZATOR_ID)
);


CREATE TABLE PROGRAM(
    PROGRAM_ID NUMBER(5),
    EVENIMENT_ID NUMBER(5),
    TITLU VARCHAR2(255),
    DESCRIERE VARCHAR2(255), 
    DATA_INCEPUT DATE NOT NULL,
    DATA_FINAL DATE NOT NULL, 
    CONSTRAINT CHEIE_PRIM_PROG PRIMARY KEY (PROGRAM_ID),
    CONSTRAINT fk_ev_pr FOREIGN KEY (EVENIMENT_ID) REFERENCES EVENIMENT(EVENIMENT_ID)
);

CREATE TABLE PRESTATIE_ARTIST(
    PRESTATIE_ID NUMBER(5),
    PROGRAM_ID NUMBER(5),
    ARTIST_ID NUMBER(5),
    ORA_PARTICIPARE DATE NOT NULL,
    DURATA_PRESTATIE NUMBER(5) NOT NULL,
    ROL_ARTIST VARCHAR2(100) NOT NULL,
    PRIMARY KEY (PRESTATIE_ID),
    FOREIGN KEY (PROGRAM_ID) REFERENCES PROGRAM(PROGRAM_ID),
    FOREIGN KEY (ARTIST_ID) REFERENCES ARTIST(ARTIST_ID)
);

CREATE TABLE PARTICIPANT(
    PARTICIPANT_ID NUMBER(5),
    NUME VARCHAR2(20) NOT NULL,
    PRENUME VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(255) NOT NULL UNIQUE,
    TELEFON NUMBER(10),
    CONSTRAINT CHEIE_PRIM_PART PRIMARY KEY (PARTICIPANT_ID)
);

CREATE TABLE RECENZIE(
    RECENZIE_ID NUMBER(5),
    PARTICIPANT_ID NUMBER(5),
    EVENIMENT_ID NUMBER(5),
    TEXT VARCHAR2(255) NOT NULL,
    RATING NUMBER(2) NOT NULL,
    CONSTRAINT CHEIE_PRIM_RECEN PRIMARY KEY (RECENZIE_ID),
    CONSTRAINT fk_part_recenzie FOREIGN KEY (PARTICIPANT_ID) REFERENCES PARTICIPANT(PARTICIPANT_ID),
    CONSTRAINT fk_even_recenzie FOREIGN KEY (EVENIMENT_ID) REFERENCES EVENIMENT(EVENIMENT_ID),
    CONSTRAINT chk_rating CHECK (rating BETWEEN 1 AND 5)
);


CREATE TABLE TIP_BILET(
    TIP_BILET_ID NUMBER(5) PRIMARY KEY,
    EVENIMENT_ID NUMBER(5),
    NUME_TIP VARCHAR2(50) NOT NULL,         
    PRET NUMBER(10,2) NOT NULL,
    DESCRIERE VARCHAR2(200),
    LOCURI_DISPONIBILE NUMBER(10),  
    FOREIGN KEY (EVENIMENT_ID) REFERENCES EVENIMENT(EVENIMENT_ID)
);


CREATE TABLE PLATA(
    PLATA_ID NUMBER(5) PRIMARY KEY,
    PARTICIPANT_ID NUMBER(5),
    METODA_PLATA VARCHAR2(50) NOT NULL, 
    SUMA_TOTALA NUMBER(10,2) NOT NULL,
    DATA_PLATA TIMESTAMP,
    STATUS_PLATA VARCHAR2(30) DEFAULT 'Confirmata',
    FOREIGN KEY (PARTICIPANT_ID) REFERENCES PARTICIPANT(PARTICIPANT_ID)
);


CREATE TABLE BILET(
    BILET_ID NUMBER(5),
    PLATA_ID NUMBER(5), 
    PARTICIPANT_ID NUMBER(5),
    TIP_BILET_ID NUMBER(5),
    PRIMARY KEY (BILET_ID), 
    FOREIGN KEY (PLATA_ID) REFERENCES PLATA(PLATA_ID),
    FOREIGN KEY (PARTICIPANT_ID) REFERENCES PARTICIPANT(PARTICIPANT_ID),
    FOREIGN KEY (TIP_BILET_ID) REFERENCES TIP_BILET(TIP_BILET_ID)
);
